name: Build DLLs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: montymintypie/llvm-mingw-xp:22

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Setup meson/ninja
        run: python -m pip install meson ninja

      - name: Build
        run: |
          meson setup build --cross-file /opt/llvm-mingw/toolchain-files/meson/i686-mingw32-clang.ini
          meson compile -C build

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jubeat-patcher
          path: build/**/*.dll
